### PR TITLE
Add support for coding standard

### PR DESCRIPTION
**Pull request by xcompass**
Also changed a few packages to use version instead of latest. It seems pear remote-info return the latest beta version and pear upgrade --force won't upgrade to that version. Puppet will generate active notifications on every run.

### CODE REVIEW

**Comment by rafaelfelix** [comment]
I got this error message trying to use your version:

could not create resource of unknown type vcsrepo at /vagrant/manifests/init.pp:128 on node vagrant-c5-x86_64

I think your pull request is missing this resource type, am I right?

**Comment by xcompass** [comment]
I added dependency in the Modulefile and readme. Also did some clean up.

**Comment by rafaelfelix** [comment]
Great! Although I had this issue when I ran this version: 

[root@localhost modules]# puppet apply -e "include phpqatools" --modulepath /root/modules/
interning empty string at /root/modules/phpqatools/manifests/init.pp:125 on node localhost.localdomain

This line refers to this test: 

if defined($default_standard) {

I usually perform this validation with a test like this: if $default_standard != undef {

**Comment by xcompass** [comment]
Fixed

**Comment by rafaelfelix** [comment]
Thanks! Excelent contribution!

**Comment by rafaelfelix** [comment]
I've just released your contribution as a new release: http://forge.puppetlabs.com/rafaelfc/phpqatools

**Comment by xcompass** [comment]
Thanks. Glad I can help :)

Cheers,
Pan

**Pull request merged**
